export const empleadosData = [
    {
        id: 1,
        apodo: "Mono",
        nombre: "Villagra, Roque Armando",
        dni: 11207754,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 2,
        apodo: "Rodrigo",
        nombre: "Fayos, Rodrigo Sebastián",
        dni: 25165321,
        disponible: false,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 3,
        apodo: "Cristian",
        nombre: "Martínez, Cristian Raúl",
        dni: 33690045,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 4,
        apodo: "Manguera",
        nombre: "Figueroa, Vicente Horacio",
        dni: 17360835,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 5,
        apodo: "Matías",
        nombre: "Galián, Pablo Matías Inocencio",
        dni: 31577940,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 6,
        apodo: "Abel",
        nombre: "Sánchez, Ángel Abel",
        dni: 26675402,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
    {
        id: 7,
        apodo: "Pablo",
        nombre: "Toro, Pablo Guillermo",
        dni: 32963681,
        disponible: true,
        viajes: {
            mar23: [],
            abr23: [],
            may23: [],
            jun23: [],
            jul23: [],
            ago23: [],
            sep23: [],
            oct23: [],
            nov23: [],
            dic23: [],
        },
        viajeActual: "Proyecto",
        unidadActual: "AG 010 SM"
    },
];